### ISSUE TITLE
The POM for com.bericotech:clavin-nerd:jar:2.1.0-SNAPSHOT is missing, no dependency information available

### ISSUE THREAD

**Issue by kiddle** [Berico-Technologies/CLAVIN-rest#8]
Hi,

Can't get CLAVIN-rest to build. Anyone else came across this issue?

Thanks!

$ mvn --version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T12:29:23-05:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"

$ mvn -U package -e                                                                                                                                  
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building clavin-rest 0.3.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.bericotech:clavin-nerd:jar:2.1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.634 s
[INFO] Finished at: 2015-02-26T08:33:31-05:00
[INFO] Final Memory: 6M/215M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project clavin-rest: Could not resolve dependencies for project com.bericotech:clavin-rest:jar:0.3.0-SNAPSHOT: Could not find artifact com.bericotech:clavin-nerd:jar:2.1.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project clavin-rest: Could not resolve dependencies for project com.bericotech:clavin-rest:jar:0.3.0-SNAPSHOT: Could not find artifact com.bericotech:clavin-nerd:jar:2.1.0-SNAPSHOT
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:220)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.bericotech:clavin-rest:jar:0.3.0-SNAPSHOT: Could not find artifact com.bericotech:clavin-nerd:jar:2.1.0-SNAPSHOT
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 22 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact com.bericotech:clavin-nerd:jar:2.1.0-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 23 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.bericotech:clavin-nerd:jar:2.1.0-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 24 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.bericotech:clavin-nerd:jar:2.1.0-SNAPSHOT
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
	... 26 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by snmvaughan** [comment]
I suspect this is an issue where the development SNAPSHOT of clavin-nerd
isn't published into the public repo.  We'll take a look this morning.

**Comment by jglesner** [comment]
The snapshots

**Comment by jglesner** [comment]
We discovered there was a mistake in the POM in master; it should not have been pointing to our internal snapshot builds.  I have changed the POM to reference the CLAVIN Nerd 2.0.0 maven central release. Please let me know if you have any other issues.
